version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: ls -al
      - run: npm run build
      - run: ls -al
      - run: cat tsconfig.json
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - dist
          key: dist-{{ checksum "package.json" }}
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dist-{{ checksum "package.json" }}
            - v1-dependencies-{{ checksum "package.json" }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ls -al
      - run: npm publish --access public

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
